package ro.sapientia.oop.course10.exceptions;public class MainExceptions {
}
